secret:
  env:
    secret:
      'secret-env-db-postgresql':
        data:
          # Connection string components
          PG_SECRET_USERNAME: 'uot-jqggp-ks8vx'
          PG_SECRET_PASSWORD: 'OY3qrFMX40ipgP5JkvJjfT1q8Bb'
          PG_SECRET_HOST: 'uot-jqggp-xmc47.coboi2otdxqo.us-gov-west-1.rds.amazonaws.com'
          PG_SECRET_PORT: '5432'
          PG_SECRET_DATABASE: 'uot'
          PG_SECRET_SSL_MODE: 'require'
          
          # Constructed connection string
          SECRET_ENV_POSTGRESQL: 'postgresql://{{ (index $.Values.secret.env.secret "secret-env-db-postgresql").data.PG_SECRET_USERNAME }}:{{ (index $.Values.secret.env.secret "secret-env-db-postgresql").data.PG_SECRET_PASSWORD }}@{{ (index $.Values.secret.env.secret "secret-env-db-postgresql").data.PG_SECRET_HOST }}:{{ (index $.Values.secret.env.secret "secret-env-db-postgresql").data.PG_SECRET_PORT }}/{{ (index $.Values.secret.env.secret "secret-env-db-postgresql").data.PG_SECRET_DATABASE }}?sslmode={{ (index $.Values.secret.env.secret "secret-env-db-postgresql").data.PG_SECRET_SSL_MODE }}'
          
          DIALECT: 'postgres'