--liquibase formatted sql
--changeset slair:2025_07_17-01-create_marketplace_order_table

CREATE TABLE marketplace_order (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requestor_id INTEGER REFERENCES marketplace_user(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status_id INTEGER REFERENCES status(id)
);