--liquibase formatted sql
--changeset slair:2025_07_16-01-create_marketplace_user_table

CREATE TABLE marketplace_user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(128) UNIQUE NOT NULL,
    advana_user_id VARCHAR(128) UNIQUE,
    first_name VARCHAR(64),
    last_name VARCHAR(64),
    agency VARCHAR(128),
    designation VARCHAR(128)
);
