--liquibase formatted sql
--changeset slair:2025_07_17-04-create_decision_table

CREATE TABLE Decision (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_number VARCHAR(32) UNIQUE NOT NULL,
    adjudicator_id INTEGER REFERENCES marketplace_user(id) NOT NULL,
    request_id INTEGER REFERENCES use_case_request(id) NOT NULL,
    order_id INTEGER REFERENCES marketplace_order(id),
    status_id INTEGER REFERENCES status(id) NOT NULL,
    ticket_type VARCHAR(64),
    asset VARCHAR(128),
    quantity INTEGER,
    estimated_price NUMERIC(18, 2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decision_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    comments VARCHAR(1024) NOT NULL
);