include:
  - project: promotion/tekton-promotion-gitlab
    file: routes/dragon-full.yml

variables:
  HELM_CHART_DIR: "./chart"
  DOCKERFILE_PATH: "./Dockerfile"
  UPSTREAM_PROJECT_DIR: "."
  HELM_RELEASE_NAME: "advana-marketplace-monolith-node"