include:
  - project: promotion/tekton-promotion-gitlab
    file: routes/dragon-full.yml
    rules:
      # Only include the review route/deployment config when:
      # 1. It's an MR pipeline
      # 2. It's a manual pipeline run where REVIEW_DEPLOYMENT = true
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      - if: $CI_PIPELINE_SOURCE == "web" && $REVIEW_DEPLOYMENT == 'true'

variables:
  HELM_CHART_DIR: "./chart"
  HELM_UPGRADE_EXTRA_ARGS: >-
    --set image.tag=${CI_COMMIT_SHA}
  DOCKERFILE_PATH: "./Dockerfile"
  UPSTREAM_PROJECT_DIR: "."
  KANIKO_EXTRA_ARGS: >-
    --build-arg=BASE_IMAGE=231388672283.dkr.ecr.us-gov-west-1.amazonaws.com/cgr.dev/odcfo-advana-bah/node-fips:22
    --build-arg=APP_UID=65532
    --build-arg=APP_GID=65532
    --build-arg=APPLICATION_VERSION="$(echo -n $(sed -n 's/appVersion: "\(.*\)"/\1/p' "chart/Chart.yaml") && echo -n ".${CI_COMMIT_SHA}" | cut -c1-9)"
