ARG BASE_IMAGE=bitnami/node:latest
FROM ${BASE_IMAGE} AS cli
ENV NODE_ENV=development
WORKDIR /app
# (root by default) -> no permission issues
COPY package*.json ./
RUN npm ci --prefer-offline            
COPY . .

FROM ${BASE_IMAGE} AS build

# build stage should use -dev image to RUN commands
# https://edu.chainguard.dev/chainguard/chainguard-images/overview/#why-minimal-container-images
#FROM "${BASE_IMAGE}-dev" AS build

ENV NODE_ENV=development

WORKDIR /app

COPY package*.json package-lock.json ./
RUN npm ci --prefer-offline
COPY . .
RUN npm run build && npm prune --omit=dev
# Debug if needed:
# RUN echo "=== BUILD ARTIFACTS ===" && ls -R dist

FROM ${BASE_IMAGE} AS runtime
ENV DIALECT=postgres

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/package*.json ./dist/
COPY --from=build /app/node_modules ./dist/node_modules
COPY --from=build /app/public ./dist/public
COPY --from=build /app/src ./dist/src

WORKDIR /app/dist

EXPOSE 8082
CMD ["node", "index.js"]
