networks:
  app-network:
    driver: bridge

volumes:
  pgdata:

services:
  app:
    container_name: advana-marketplace-monolith-node
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    environment:
      # Main app uses this
      SECRET_ENV_POSTGRESQL: "postgres://postgres:password@postgres:5432/advana-marketplace-monolith-db"
      # Tests use this
      DATABASE_URL: "postgres://postgres:password@postgres:5432/advana-marketplace-monolith-db"
      SEQUELIZE_LOG_SQL: "true"
      CORS_ORIGIN: "http://localhost:8080"
      KEYCLOAK_BASE_URL: "http://kubernetes.docker.internal:8083"
      KEYCLOAK_REALM: "marketplace"
      KEYCLOAK_CLIENT_ID: "marketplace-be"
      KEYCLOAK_CLIENT_SECRET: "fillme"
      MARKETPLACE_ADJUDICATOR_ROLE: "marketplace-approver"
      MARKETPLACE_REQUESTOR_ROLE: "marketplace-requestor"
      MARKETPLACE_BYPASS_AUTH: false
      USE_CLIENT_SESSION_STORAGE: true
      INTROSPECT_AUTH: basic
      INTROSPECT_RETRY: true       
      INTROSPECT_TIMEOUT_MS: 5000
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - app-network
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - POSTGRES_DB=advana-marketplace-monolith-db
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d advana-marketplace-monolith-db -U postgres",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
 