--liquibase formatted sql
--changeset slair:2025_08_06-02-create_cart_item_table

CREATE TABLE cart_item (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	request_id INTEGER REFERENCES use_case_request(id) NOT NULL,
    product_id INTEGER REFERENCES product(id) NOT NULL,
    quantity INTEGER,
    CONSTRAINT unique_request_product_for_cart_item UNIQUE(product_id, request_id)
);