--liquibase formatted sql
--changeset slair:2025_07_17-03-create_order_item_table

CREATE TABLE order_item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER REFERENCES marketplace_order(id),
    product_id INTEGER REFERENCES product(id),
    justification VARCHAR(1024) NOT NULL
);