--liquibase formatted sql
--changeset slair:2025_07_17-02-create_product_table

CREATE TABLE product (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) UNIQUE NOT NULL,
    vendor VARCHAR(128),
    description VARCHAR(1024)
);