--liquibase formatted sql
--changeset slair:2025_07_16-05-create_use_case_request_table

CREATE TABLE use_case_request (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number VARCHAR(32) UNIQUE NOT NULL,
    requestor_id INTEGER REFERENCES marketplace_user(id) NOT NULL,
    designation VARCHAR(128),
    agency VARCHAR(128),
    organization VARCHAR(128),
    other_organization VARCHAR(128),
    point_of_contact VARCHAR(128),
    phone_number VARCHAR(32),
    email VARCHAR(128),
    estimated_rom VARCHAR(32),
    requested_tool_name VARCHAR(128) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status_id INTEGER REFERENCES status(id) NOT NULL
);